### PR TITLE
fix: Implement gec, localised form error

### LINKED ISSUE #511: Localise: Form Submission Error should be shown based on locale.
Currently the form submission error are hardcoded in english, we should shown them in localise text.

### PR DESCRIPTION
**Pull request by Pareesh**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #511 #501

Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/contact/
- After: https://error--mammotome--hlxsites.hlx.page/us/en/contact/
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
- After: https://error--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/submit-a-tech-support-ticket
- After: https://error--mammotome--hlxsites.hlx.page/us/en/submit-a-tech-support-ticket
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/innovate-with-mammotome
- After: https://error--mammotome--hlxsites.hlx.page/us/en/about-us/innovate-with-mammotome
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/investigator-initiated-study-request
- After: https://error--mammotome--hlxsites.hlx.page/us/en/about-us/investigator-initiated-study-request
- Before: https://main--mammotome--hlxsites.hlx.page/fr/fr/contact
- After: https://error--mammotome--hlxsites.hlx.page/fr/fr/contact
- Before: https://main--mammotome--hlxsites.hlx.page/es/es/contacto
- After: https://error--mammotome--hlxsites.hlx.page/es/es/contacto
- Before: https://main--mammotome--hlxsites.hlx.page/it/it/referente
- After: https://error--mammotome--hlxsites.hlx.page/it/it/referente
- Before: https://main--mammotome--hlxsites.hlx.page/de/de/kontakt
- After: https://error--mammotome--hlxsites.hlx.page/de/de/kontakt

### CODE REVIEW

File: blocks/form/form.js [hunk 1]
```diff
@@ -99,23 +103,32 @@ async function submitForm(form, token) {
...
+      const dictionary = window.placeholders.default[`i18n-${locale}`];
+      const error = dictionary[`formSubmissionError-${response.status}`] || dictionary.formSubmissionError;
       throw new Error(error);
     }
   } catch (error) {
     submissionFailure(error, form);
   }
 }
 
+function addGEC(form) {
```
Comment (solaris007) [inline blocks/form/form.js:116]: prefer guard clause:

```
function addGEC(form) {
  const email = form.querySelector('input[name=email]');
  
  if (!email) return;

  window.dataLayer = window.dataLayer || [];
  window.dataLayer.push({
    event: 'form_complete',
    enhanced_conversion_data: { email: email.value },
  });
}
```

**Review by solaris007 — APPROVED** [review]

File: blocks/form/form.js [hunk 2]
```diff
@@ -8,6 +8,10 @@ import decorateUTM from './utm.js';
 const SITE_KEY = '6Lc0qYoiAAAAADNOimWbvoSdn2YawNsa6Wbxejpp';
 const FORM_SUBMIT_ENDPOINT = 'https://franklin-submit-wrapper.mammotome.workers.dev';
 
+function getLocaleRegion() {
+  return (getMetadata('locale') || 'en-US').split('-');
```
Comment (jalagari) [inline blocks/form/form.js:12]: Before it was en and now default is en-US. Is it expected change?

**Review by jalagari — APPROVED** [review]

File: blocks/form/form.js (hunk 2 above)
Comment (Pareesh) [reply blocks/form/form.js:12]: The default value in metadata sheet has been changed to `en-US` that why I updated the value.
