### PR TITLE
fix: checkbox with same name not working correctly when required

### LINKED ISSUE #397: bug(form): same name checkbox with required working incorrectly.
This issue corresponds to the one raised here :  https://cq-dev.slack.com/archives/C04TVNL3S3W/p1688041784670699

### PR DESCRIPTION
**Pull request by Pareesh**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #397

Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/about-us/innovate-with-mammotome
- After: https://formbug--mammotome--hlxsites.hlx.page/us/en/about-us/innovate-with-mammotome
- Before: https://main--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo
- After: https://formbug--mammotome--hlxsites.hlx.page/us/en/schedule-a-demo

### CODE REVIEW

File: blocks/form/checkbox.js [hunk 1]
```diff
@@ -0,0 +1,27 @@
+function update(checkboxgroup, isChecked) {
+  if (isChecked) { // remove required if any of them is checked
+    checkboxgroup.forEach((checkbox) => checkbox.removeAttribute('required'));
+  } else if (checkboxgroup.every((checkbox) => !checkbox.checked)) {
+    // set required if none of them is checked
+    checkboxgroup.forEach((checkbox) => checkbox.setAttribute('required', ''));
+  }
+}
+
+export default async function decorate(form) {
```
Comment (solaris007) [inline blocks/form/checkbox.js:10]: you could probably remove the `event.target.checked` and simplify the `update` signature, effectively making it a toggle-behavior. 

also, `Array.from` makes the code more readable:

```
export default async function decorate(form) {
  const checkboxes = Array.from(form.querySelectorAll('input[type=checkbox][required]'));
  const checkboxNameMap = checkboxes.reduce((map, checkbox) => {
    if (map.has(checkbox.name)) {
      map.get(checkbox.name).push(checkbox);
    } else {
      map.set(checkbox.name, [checkbox]);
    }
    return map;
  }, new Map());

  Array.from(checkboxNameMap.values())
    .filter((checkboxgroup) => checkboxgroup.length > 1)
    .forEach((checkboxgroup) => {
      checkboxgroup.forEach((checkbox) => {
        checkbox.onchange = () => update(checkboxgroup);
      });
    });
}
```

**Review by solaris007 — APPROVED** [review]

File: blocks/form/checkbox.js [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+  const checkboxes = form.querySelectorAll('input[type=checkbox][required]');
+  const checkboxNameMap = [...checkboxes].reduce((map, checkbox) => {
+    if (map.has(checkbox.name)) {
+      map.get(checkbox.name).push(checkbox);
+    } else {
+      map.set(checkbox.name, [checkbox]);
+    }
+    return map;
```
Comment (vdua) [inline blocks/form/checkbox.js:20]:
```
[...checkboxes].reduce((map, checkbox) => ({
   ...map
   [checkbox.name] : [checkbox, ...(map[checkbox.name] || [] )]   
}), {})
```

File: blocks/form/checkbox.js [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+  }, new Map());
+
+  Array.from(checkboxNameMap.values())
```
Comment (vdua) [inline blocks/form/checkbox.js:23]: Please use a single syntax. `Array.from` or `spread` (...) operator

File: blocks/form/checkbox.js [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+    .filter((checkboxgroup) => checkboxgroup.length > 1)
+    .forEach((checkboxgroup) => {
+      checkboxgroup.forEach((checkbox) => {
+        checkbox.onchange = () => update(checkboxgroup);
+      });
+    });
```
Comment (vdua) [inline blocks/form/checkbox.js:29]: Another way could be to identify checkboxes with same name.

```
[...new Set([...checkboxes].map(x.name))].forEach(name => {
   const cbs = document.getElementsByName(name);
   if (cbs.length > 1) 
            cbs.forEach(checkbox => checkbox.addEventListener('change', update())
})
```

File: blocks/form/checkbox.js [hunk 5]
```diff
@@ -0,0 +1,30 @@
+function update(checkboxgroup) {
+  const allUnchecked = checkboxgroup.every((checkbox) => !checkbox.checked);
```
Comment (vdua) [inline blocks/form/checkbox.js:2]: you can access all the checkboxes using `document.getElementsByName(e.target.name)`

**Review by vdua — CHANGES_REQUESTED** [review]

File: blocks/form/checkbox.js (hunk 4 above)
Comment (Pareesh) [reply blocks/form/checkbox.js:29]: I will adjust the code with this approach.

File: blocks/form/checkbox.js (hunk 2 above)
Comment (Pareesh) [reply blocks/form/checkbox.js:20]: using `getElementsByName` removing this code

File: blocks/form/checkbox.js (hunk 4 above)
Comment (Pareesh) [reply blocks/form/checkbox.js:29]: `getElementsByName` is available only on document. I think the same named checkboxes validation should be done per form level. Moving back to `map` will incorporate above implementation of map/object.

File: blocks/form/checkbox.js (hunk 2 above)
Comment (Pareesh) [reply blocks/form/checkbox.js:20]: Will be using this implementation, since `getElementsByName` is available only on document and same name checkbox validation should be done by per form.

Comment (Pareesh) [reply blocks/form/checkbox.js]: done

File: blocks/form/checkbox.js (hunk 5 above)
Comment (Pareesh) [reply blocks/form/checkbox.js:2]: same named checkbox already stored in closure, passing them

**Review by solaris007 — DISMISSED** [review]

File: blocks/form/form.js [hunk 6]
```diff
@@ -86,7 +87,12 @@ async function submitForm(form, token) {
       sampleRUM('form:submit');
       window.location.href = form.dataset?.redirect || '/us/en/thankyou';
     } else {
-      const error = await response.text();
+      let error;
+      try {
+        error = (await response.json()).message;
```
Comment (jalagari) [inline blocks/form/form.js:92]: Minor- add default error message in can its empty

File: blocks/form/form.css [hunk 7]
```diff
@@ -313,7 +317,7 @@ main .connectus .form-consent {
 }
 
 /* stylelint-disable-next-line  selector-class-pattern */
-main .connectus :is(.form-company, .form-Pardot_Form_Message__c, .form-description, .form-consent) {
+main .connectus :is(.form-companyName, .form-Pardot_Form_Message__c, .form-description, .form-consent) {
```
Comment (jalagari) [inline blocks/form/form.css:320]: Marketo expects the field name to be company. Since company H1 is already exists in same page accessibility score was less and @solaris007 changed it to companyName.

At time of generating payload we should replace companyName to company.

@vdua - We decided to use the name of field as component id, should we add prefix (may in other project) to avoid such conflicts?

Comment (Pareesh) [reply blocks/form/form.css:320]: Hi @jalagari,
Sorry, I am not able to understand what exactly needs to be done.

**Review by solaris007 — DISMISSED** [review]

**Review by jalagari — APPROVED** [review]

**Review by jalagari — APPROVED** [review]
