### PR TITLE
fix: active nav highlighting

### LINKED ISSUE #147: Highlight active page in top nav
The top nav needs to highlight (background)  the current visible page:

screeni2305

### PR DESCRIPTION
**Pull request by Acidham**
Add active link highlighting for MultiNav (typical product pages) and refactor tab-navigation.js → move setActiveLink function to franklin lib

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #147 

Test URLs:
- Before: https://main--mammotome--hlxsites.hlx.page/en/

After: 
- https://147-highlight-active-page-in-top-nav--mammotome--hlxsites.hlx.page/en/
- https://147-highlight-active-page-in-top-nav--mammotome--hlxsites.hlx.page/en/patient-resources/understanding-biopsy-results

### CODE REVIEW

File: scripts/lib-franklin.js [hunk 1]
```diff
@@ -693,6 +693,22 @@ export function decorateTemplateAndTheme() {
   if (theme) addClasses(document.body, theme);
 }
 
+/**
+ * Set Link class to active when on the same page
+ * @param links {NodeListOf<Element>} Array of links to check
+ * @param className {string} Class to add to active link
+ */
+export function setActiveLink(links, className) {
+  if (!links.length) return;
```
Comment (solaris007) [inline scripts/lib-franklin.js:702]: should also check for zero length:
```
if (!links || links.length === 0) return;
```

File: scripts/lib-franklin.js [hunk 2]
```diff
@@ -693,6 +693,22 @@ export function decorateTemplateAndTheme() {
...
+  const actualPage = getMetadata('og:url').split('/').slice(-1)[0].toLowerCase();
+  links.forEach((a) => {
+    const href = a.getAttribute('href') ? a.getAttribute('href').toLowerCase() : '';
```
Comment (solaris007) [inline scripts/lib-franklin.js:705]: you can minimize DOM access by combining `getAttribute` into one call:
```
const href = (a.getAttribute('href') || '').toLowerCase();
```

**Comment by solaris007** [comment]
i am seeing a slight increase in CLS - related?

**Comment by Acidham** [comment]
> i am seeing a slight increase in CLS - related?

The setActiveLink is not influencing any CLS. seems to be related to hero moving image up slightly?

**Review by solaris007 — APPROVED** [review]
